export let AppKey : any = 'vtexappkey-tonypapelerias-DRPNKY'
export let AppToken : any  = 'JIJRSLWRBSPJPOFZPTJTLSYXNLPYQGYAKPHFCFEFXLMXFGUEDDQJPZORKMDHVYBVTOYZGAXJODVZGARHRLUMPOKLAQUPCXJZKQEQHUXDFHVLDPLKUWQKDOFEDNYQFIGR'
